# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'ubuntu_dev'
  config.vm.box_url = '../boxes/ubuntu_dev.box'

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder 'vendor_artifacts', '/vendor_artifacts', '../vendor_artifacts'
  config.vm.share_folder 'deployscripts_infrastructure', '/deployscripts_infrastructure', '../deployscripts_infrastructure'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['../../infrastructure/cookbooks', '../../cookbooks', '../../rightscale_cookbooks']
    chef.add_recipe 'apache2'
    chef.add_recipe 'passenger'
    chef.add_recipe 'deployment_services'

    # You may also specify custom JSON attributes:
    #chef.json = { :core => {
    #  :aws_access_key_id => '',
    #  :aws_secret_access_key => ''
    #  }
    #}
  end
end
